#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: 750e50d
#
Name     : input-leap
Version  : 6446288aa619133f287cf3166bc924a99d073ea2
Release  : 2
URL      : https://github.com/input-leap/input-leap/archive/6446288aa619133f287cf3166bc924a99d073ea2/input-leap-6446288aa619133f287cf3166bc924a99d073ea2.tar.gz
Source0  : https://github.com/input-leap/input-leap/archive/6446288aa619133f287cf3166bc924a99d073ea2/input-leap-6446288aa619133f287cf3166bc924a99d073ea2.tar.gz
Source1  : https://github.com/gulrak/filesystem/archive/v1.5.14/gulrak-filesystem-1.5.14.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT OpenSSL
Requires: input-leap-bin = %{version}-%{release}
Requires: input-leap-data = %{version}-%{release}
Requires: input-leap-license = %{version}-%{release}
Requires: input-leap-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : googletest-dev
BuildRequires : pkgconfig(avahi-compat-libdns_sd)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmock)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libei-1.0)
BuildRequires : pkgconfig(libportal)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xtst)
BuildRequires : qttools-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Input Leap
<!-- add CI badges, flatpak, snap, use github actions badges or Azure? Decide on
*one* -->

%package bin
Summary: bin components for the input-leap package.
Group: Binaries
Requires: input-leap-data = %{version}-%{release}
Requires: input-leap-license = %{version}-%{release}

%description bin
bin components for the input-leap package.


%package data
Summary: data components for the input-leap package.
Group: Data

%description data
data components for the input-leap package.


%package license
Summary: license components for the input-leap package.
Group: Default

%description license
license components for the input-leap package.


%package man
Summary: man components for the input-leap package.
Group: Default

%description man
man components for the input-leap package.


%prep
%setup -q -n input-leap-6446288aa619133f287cf3166bc924a99d073ea2
cd %{_builddir}
tar xf %{_sourcedir}/gulrak-filesystem-1.5.14.tar.gz
cd %{_builddir}/input-leap-6446288aa619133f287cf3166bc924a99d073ea2
mkdir -p ext/gulrak-filesystem
cp -r %{_builddir}/filesystem-1.5.14/* %{_builddir}/input-leap-6446288aa619133f287cf3166bc924a99d073ea2/ext/gulrak-filesystem

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707078673
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake .. -DINPUTLEAP_USE_EXTERNAL_GTEST=YES
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DINPUTLEAP_USE_EXTERNAL_GTEST=YES
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test
cd ../clr-build-avx2;
make test || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707078673
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/input-leap
cp %{_builddir}/filesystem-1.5.14/LICENSE %{buildroot}/usr/share/package-licenses/input-leap/fb35a530cb1bb57a2cfe303bf68bb6ce4a404fb0 || :
cp %{_builddir}/input-leap-%{version}/dist/debian/copyright %{buildroot}/usr/share/package-licenses/input-leap/4fc1bf5636b8011298525d56786cb7dff0de7018 || :
cp %{_builddir}/input-leap-%{version}/ext/openssl/LICENSE %{buildroot}/usr/share/package-licenses/input-leap/102073b66c9be39953f62af2eb238629f7d50883 || :
cp %{_builddir}/input-leap-%{version}/res/License.rtf %{buildroot}/usr/share/package-licenses/input-leap/f801798afe701ce87c20062a6a514d1ab7bf5185 || :
cp %{_builddir}/input-leap-%{version}/res/License.tex %{buildroot}/usr/share/package-licenses/input-leap/28c8b9f7de43754bf7dfa7ddef3dabd54d257cd2 || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/input-leap
/V3/usr/bin/input-leapc
/V3/usr/bin/input-leaps
/usr/bin/input-leap
/usr/bin/input-leapc
/usr/bin/input-leaps

%files data
%defattr(-,root,root,-)
/usr/share/applications/input-leap.desktop
/usr/share/icons/hicolor/scalable/apps/input-leap.svg
/usr/share/metainfo/input-leap.appdata.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/input-leap/102073b66c9be39953f62af2eb238629f7d50883
/usr/share/package-licenses/input-leap/28c8b9f7de43754bf7dfa7ddef3dabd54d257cd2
/usr/share/package-licenses/input-leap/4fc1bf5636b8011298525d56786cb7dff0de7018
/usr/share/package-licenses/input-leap/f801798afe701ce87c20062a6a514d1ab7bf5185
/usr/share/package-licenses/input-leap/fb35a530cb1bb57a2cfe303bf68bb6ce4a404fb0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/input-leapc.1
/usr/share/man/man1/input-leaps.1
